name: Build and Validate Docker App

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v3

      - name: Construir imagen de la app
        run: docker build -t bienestar-u-app .

      - name: Validar docker-compose.yml
        run: docker-compose config
